# Generated by Django 3.2.3 on 2021-05-31 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=4096, verbose_name='Info')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('approved_at', models.DateTimeField(null=True, verbose_name='Approved at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='hiring.category', verbose_name='Category')),
                ('files', models.ManyToManyField(to='hiring.File', verbose_name='Files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='bot.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(null=True, verbose_name='Approved at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requests', to='hiring.resume', verbose_name='Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requests', to='bot.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Hiring request',
                'verbose_name_plural': 'Hiring requests',
            },
        ),
    ]
