# Generated by Django 3.2.3 on 2021-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_auto_20210604_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='request_id',
            field=models.IntegerField(null=True, verbose_name='Request id'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='info',
            field=models.CharField(max_length=4000, null=True, verbose_name='Info'),
        ),
    ]
