# Generated by Django 3.2.3 on 2021-06-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_auto_20210604_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='files',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='info',
        ),
        migrations.AddField(
            model_name='resume',
            name='additional_info',
            field=models.TextField(null=True, verbose_name='Additional info'),
        ),
        migrations.AddField(
            model_name='resume',
            name='driver_license',
            field=models.BooleanField(null=True, verbose_name='Driver license'),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(null=True, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='resume',
            name='instagram',
            field=models.CharField(max_length=200, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(null=True, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='resume',
            name='ready_for_business_trips',
            field=models.BooleanField(null=True, verbose_name='Ready for business trips'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(null=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.TextField(null=True, verbose_name='Work experience'),
        ),
    ]
