# Generated by Django 3.2.3 on 2021-06-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_auto_20210612_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringrequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='resume',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
