# Generated by Django 3.2.3 on 2021-06-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_auto_20210612_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiringrequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Hiring request', 'verbose_name_plural': 'Hiring requests'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-filled_out_at',), 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='message_id',
            field=models.IntegerField(null=True, verbose_name='Message id'),
        ),
    ]
